version: '2.0'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rkaalswo123
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
  mongodb:
    image: mongo
    ports:
    -  "27017:27017"
