---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      name: nodeapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 8080
