#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test
#    username: root
#    password: rkaalswo123
#    driverClassName: com.mysql.cj.jdbc.Driver